import { randomBytes } from 'node:crypto';
import { writeFileSync, existsSync } from 'node:fs';
import { loadEnv } from 'vite';
const origin = process.argv[2];
if (!origin || new URL(origin).origin !== origin || !origin.startsWith('https://')) throw new Error('Informe a origem HTTPS exata.');
if (existsSync('.env.production.local') || existsSync('ACESSO-VPS.local')) throw new Error('Credenciais existentes preservadas. Use os arquivos já preparados.');
const env = loadEnv('production', process.cwd(), 'GROQ_');
const username = 'produtivoalex';
writeFileSync('.env.production.local', [`APP_ORIGIN=${origin}`, `ADMIN_USERNAME=${username}`, 'RECOVERY_EMAIL=produtivoalex@gmail.com', `OTP_PEPPER=${randomBytes(32).toString('hex')}`, `GROQ_API_KEY=${env.GROQ_API_KEY || ''}`, `GROQ_MODEL=${env.GROQ_MODEL || 'llama-3.3-70b-versatile'}`, 'SMTP_HOST=smtp.gmail.com', 'SMTP_PORT=465', 'SMTP_USER=produtivoalex@gmail.com', 'SMTP_PASSWORD=', 'AI_HOURLY_LIMIT=20', 'AI_DAILY_LIMIT=100', ''].join('\n'), { mode: 0o600 });
writeFileSync('ACESSO-VPS.local', `CultoGen — acesso privado\n\nEndereço: ${origin}\n\nNo primeiro acesso, confirme o email cadastrado e escolha um PIN de quatro dígitos.\nEste arquivo e a configuração de produção ficam fora do Git.\n`, { mode: 0o600 });
console.log('Configuração privada preparada. Adicione SMTP_PASSWORD à configuração da VPS antes de ativar a confirmação por email.');
